# Generated by Django 4.2.5 on 2023-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_attendees_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(default='event_username', max_length=250),
        ),
    ]
