# Generated by Django 4.2.5 on 2023-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attendee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
