# Generated by Django 4.2.5 on 2023-09-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_attendee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='name',
        ),
    ]
