# Generated by Django 4.2.5 on 2023-09-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
    ]
