# Generated by Django 4.2.5 on 2023-09-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_guests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
